### ISSUE TITLE
Homework feedback - JS1-Week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [Lucha2040/hyf-homework#4]
Hi, 
Good Job! 👍 for using Html and css here. I liked you because you think different and enjoying coding :)

Task 1 and 2 looks good. 
If you want to get the value from checkbox then look below link :
https://www.w3schools.com/jsref/prop_checkbox_checked.asp

Task 3 -
It was to show whether Peter and Julia are paying less or more compare to actual house cost.
1. Calculate VolumeInMeters
2. Calculate housePricePeter
3. Use if else statement for comparing like this :
4.  if(housePricePeter< 2500000) then 
console.log(“Peter is paying more”) else console.log(“Peter is paying less”)

Task 4 - It is missing or do you need any help for that?

Keep coding and All the best !

**Comment by Lucha2040** [comment]
Swapna thanks for checking (bare with me, I realized now that we have to check the cases and close them, I am an idiot sometimes haha). 
I will do the corrections and close the case when done, but I wanted to submit the homework so I could start preparing the materials for week2, that's why I didn't do the optional exercise 4. 
Will try to work out before sunday. 
Btw, this was the fastest correction I had. Thanks!!!!

**Comment by Lucha2040** [comment]
Modifications implemented. 
Added Exercise 4. 
On https://github.com/Lucha2040/hyf-homework/pull/31
